install.packages(
 c('devtools','ggplot2','dplyr','tidyr',
   'quantmod','leaflet','DT'),
 repos='http://repo.bppt.go.id/cran'
)
library(devtools)
install_github(
 c('rwebapps/stockapp','rwebapps/napel',
   'rwebapps/markdownapp','rwebapps/appdemo',
   'rwebapps/gitstats','rwebapps/rollcorr',
   'rwebapps/VisiStat','rwebapps/tvscore',
   'rwebapps/leafletapp')
)
