install.packages(
 c('devtools','ggplot2','dplyr','tidyr',
   'quantmod','leaflet','DT','forecast',
   'tseries'),
 repos='http://cran.r-project.org/'
)
library(devtools)
install_github(
 c('rwebapps/stockapp','rwebapps/napel',
   'rwebapps/markdownapp','rwebapps/appdemo',
   'rwebapps/gitstats','rwebapps/rollcorr',
   'rwebapps/VisiStat','rwebapps/tvscore',
   'rwebapps/leafletapp')
)
update.packages(
 ask=FALSE,
 repos='http://cran.r-project.org/'
)
